// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/orders.proto

package services

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Orders service

func NewOrdersEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Orders service

type OrdersService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Orders_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Orders_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Orders_BidiStreamService, error)
}

type ordersService struct {
	c    client.Client
	name string
}

func NewOrdersService(name string, c client.Client) OrdersService {
	return &ordersService{
		c:    c,
		name: name,
	}
}

func (c *ordersService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Orders.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersService) ClientStream(ctx context.Context, opts ...client.CallOption) (Orders_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Orders.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &ordersServiceClientStream{stream}, nil
}

type Orders_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type ordersServiceClientStream struct {
	stream client.Stream
}

func (x *ordersServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *ordersServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *ordersServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *ordersServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ordersServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ordersServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *ordersService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Orders_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Orders.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &ordersServiceServerStream{stream}, nil
}

type Orders_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type ordersServiceServerStream struct {
	stream client.Stream
}

func (x *ordersServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *ordersServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *ordersServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *ordersServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ordersServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ordersServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ordersService) BidiStream(ctx context.Context, opts ...client.CallOption) (Orders_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Orders.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &ordersServiceBidiStream{stream}, nil
}

type Orders_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type ordersServiceBidiStream struct {
	stream client.Stream
}

func (x *ordersServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *ordersServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *ordersServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *ordersServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ordersServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ordersServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *ordersServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Orders service

type OrdersHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Orders_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Orders_ServerStreamStream) error
	BidiStream(context.Context, Orders_BidiStreamStream) error
}

func RegisterOrdersHandler(s server.Server, hdlr OrdersHandler, opts ...server.HandlerOption) error {
	type orders interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Orders struct {
		orders
	}
	h := &ordersHandler{hdlr}
	return s.Handle(s.NewHandler(&Orders{h}, opts...))
}

type ordersHandler struct {
	OrdersHandler
}

func (h *ordersHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.OrdersHandler.Call(ctx, in, out)
}

func (h *ordersHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.OrdersHandler.ClientStream(ctx, &ordersClientStreamStream{stream})
}

type Orders_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type ordersClientStreamStream struct {
	stream server.Stream
}

func (x *ordersClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *ordersClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *ordersClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ordersClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ordersClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *ordersHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.OrdersHandler.ServerStream(ctx, m, &ordersServerStreamStream{stream})
}

type Orders_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type ordersServerStreamStream struct {
	stream server.Stream
}

func (x *ordersServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *ordersServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *ordersServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ordersServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ordersServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *ordersHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.OrdersHandler.BidiStream(ctx, &ordersBidiStreamStream{stream})
}

type Orders_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type ordersBidiStreamStream struct {
	stream server.Stream
}

func (x *ordersBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *ordersBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *ordersBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ordersBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ordersBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *ordersBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
