// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/products.proto

package services

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Products service

func NewProductsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Products service

type ProductsService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Products_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Products_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Products_BidiStreamService, error)
}

type productsService struct {
	c    client.Client
	name string
}

func NewProductsService(name string, c client.Client) ProductsService {
	return &productsService{
		c:    c,
		name: name,
	}
}

func (c *productsService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Products.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsService) ClientStream(ctx context.Context, opts ...client.CallOption) (Products_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Products.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &productsServiceClientStream{stream}, nil
}

type Products_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type productsServiceClientStream struct {
	stream client.Stream
}

func (x *productsServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *productsServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *productsServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productsServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *productsService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Products_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Products.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &productsServiceServerStream{stream}, nil
}

type Products_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type productsServiceServerStream struct {
	stream client.Stream
}

func (x *productsServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *productsServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *productsServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productsServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productsService) BidiStream(ctx context.Context, opts ...client.CallOption) (Products_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Products.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &productsServiceBidiStream{stream}, nil
}

type Products_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type productsServiceBidiStream struct {
	stream client.Stream
}

func (x *productsServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *productsServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *productsServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productsServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *productsServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Products service

type ProductsHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Products_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Products_ServerStreamStream) error
	BidiStream(context.Context, Products_BidiStreamStream) error
}

func RegisterProductsHandler(s server.Server, hdlr ProductsHandler, opts ...server.HandlerOption) error {
	type products interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Products struct {
		products
	}
	h := &productsHandler{hdlr}
	return s.Handle(s.NewHandler(&Products{h}, opts...))
}

type productsHandler struct {
	ProductsHandler
}

func (h *productsHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.ProductsHandler.Call(ctx, in, out)
}

func (h *productsHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.ProductsHandler.ClientStream(ctx, &productsClientStreamStream{stream})
}

type Products_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type productsClientStreamStream struct {
	stream server.Stream
}

func (x *productsClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *productsClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productsClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *productsHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ProductsHandler.ServerStream(ctx, m, &productsServerStreamStream{stream})
}

type Products_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type productsServerStreamStream struct {
	stream server.Stream
}

func (x *productsServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *productsServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productsServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *productsHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.ProductsHandler.BidiStream(ctx, &productsBidiStreamStream{stream})
}

type Products_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type productsBidiStreamStream struct {
	stream server.Stream
}

func (x *productsBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *productsBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productsBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *productsBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
